// Deterministic automatic study planner – works fully offline.
// Mirrors server/study_planner_mcp/planner.py; keep both in sync.
//
// 1. Future sessions previously generated by the planner (source auto, still
//    planned) are dropped; everything else is kept and treated as busy time.
// 2. Availability windows are cut into session-length slots (with breaks),
//    capped per day and preferring the student's preferred time of day.
// 3. Each slot goes to the best candidate: an open task (priority, deadline
//    closeness, subject weakness) or a revision session for a subject behind
//    its (need-weighted) weekly target. Revision only fills a day up to the
//    daily goal. Repeating the previous subject is penalised (interleaving).
// 4. Tasks that can't be fully scheduled before their deadline are at risk.

import 'dart:math' as math;

import '../models/planner_data.dart';
import 'analytics.dart';

const minSessionMinutes = 15;
const defaultWeeklyTarget = 120;
const _priorityWeight = {1: 1.0, 2: 2.0, 3: 3.0};

class AtRiskTask {
  AtRiskTask(this.task, this.unscheduledMinutes);
  final StudyTask task;
  final int unscheduledMinutes;
}

class PlanResult {
  PlanResult(this.sessions, this.kept, this.atRisk);
  final List<StudySession> sessions; // newly generated
  final List<StudySession> kept;
  final List<AtRiskTask> atRisk;
}

double subjectNeed(Subject subject, double strength, DateTime now) {
  var need = (1 - strength) + 0.3 * (subject.difficulty - 1) / 4;
  final exam = parseDue(subject.examDate);
  if (exam != null && !exam.isBefore(now)) {
    final days = exam.difference(now).inMinutes / 1440;
    need += math.max(0, (14 - days) / 14);
  }
  return need * subject.aiWeight.clamp(0.5, 2.0);
}

DateTime _hm(DateTime day, String value) {
  final p = value.split(':');
  final h = int.parse(p[0]);
  final m = p.length > 1 ? int.parse(p[1]) : 0;
  if (h >= 24) return DateTime(day.year, day.month, day.day + 1);
  return DateTime(day.year, day.month, day.day, h, m);
}

String _dayKey(DateTime d) => isoDate(d);

List<(DateTime, DateTime)> buildSlots(PlannerData data, DateTime now, int days, List<(DateTime, DateTime)> busy) {
  final p = data.profile;
  final length = Duration(minutes: p.sessionMinutes);
  final step = Duration(minutes: p.sessionMinutes + p.breakMinutes);
  final earliest = now.add(const Duration(minutes: 5));
  final slots = <(DateTime, DateTime)>[];
  for (var offset = 0; offset < days; offset++) {
    final day = DateTime(now.year, now.month, now.day + offset);
    final daySlots = <(DateTime, DateTime)>[];
    for (final w in p.availability[day.weekday] ?? const <TimeWindow>[]) {
      var t = _hm(day, w.start);
      final end = _hm(day, w.end);
      while (!t.add(length).isAfter(end)) {
        final slot = (t, t.add(length));
        final overlaps = busy.any((b) => slot.$1.isBefore(b.$2) && b.$1.isBefore(slot.$2));
        if (!t.isBefore(earliest) && !overlaps) daySlots.add(slot);
        t = t.add(step);
      }
    }
    final taken = busy.where((b) => _dayKey(b.$1) == _dayKey(day)).length;
    int rank((DateTime, DateTime) s) => timePeriod(s.$1.hour) == p.preferredTime ? 0 : 1;
    daySlots.sort((a, b) {
      final r = rank(a).compareTo(rank(b));
      return r != 0 ? r : a.$1.compareTo(b.$1);
    });
    final chosen = daySlots.take(math.max(0, p.maxSessionsPerDay - taken)).toList()
      ..sort((a, b) => a.$1.compareTo(b.$1));
    slots.addAll(chosen);
  }
  return slots;
}

PlanResult generatePlan(PlannerData data, DateTime now, {int days = 7}) {
  bool isFuture(StudySession s) => !s.startAt.isBefore(now);
  final kept = data.sessions
      .where((s) => !(s.source == SessionSource.auto && s.status == SessionStatus.planned && isFuture(s)))
      .toList();
  final busy = [
    for (final s in kept)
      if ((s.status == SessionStatus.planned || s.status == SessionStatus.completed) && s.endAt.isAfter(now))
        (s.startAt, s.endAt),
  ];
  final slots = buildSlots(data, now, days, busy);

  final stats = {for (final s in subjectStats(data, now)) s.subject.id: s};
  final need = {for (final s in data.subjects) s.id: subjectNeed(s, stats[s.id]!.strength, now)};

  final allocated = <String, int>{};
  for (final s in kept) {
    if (isFuture(s) && s.status == SessionStatus.planned && s.subjectId != null) {
      allocated.update(s.subjectId!, (m) => m + s.durationMinutes, ifAbsent: () => s.durationMinutes);
    }
  }

  final remaining = <String, int>{};
  final tasks = <StudyTask>[];
  for (final t in data.tasks) {
    if (t.isDone) continue;
    var left = t.estimatedMinutes - t.completedMinutes;
    for (final s in kept) {
      if (s.taskId == t.id && s.status == SessionStatus.planned && isFuture(s)) left -= s.durationMinutes;
    }
    if (left > 0) {
      remaining[t.id] = left;
      tasks.add(t);
    }
  }

  final horizonWeeks = math.max(days, 1) / 7;
  final length = data.profile.sessionMinutes;
  final goal = data.profile.dailyGoalMinutes > 0 ? data.profile.dailyGoalMinutes : 120;
  final newSessions = <StudySession>[];
  final lastSubjectByDay = <String, String>{};
  final perDaySubject = <String, int>{};
  final dayMinutes = <String, int>{};
  for (final s in kept) {
    if (s.status == SessionStatus.planned || s.status == SessionStatus.completed) {
      dayMinutes.update(_dayKey(s.startAt), (m) => m + s.durationMinutes, ifAbsent: () => s.durationMinutes);
    }
  }

  for (final (start, _) in slots) {
    final dayKey = _dayKey(start);
    final dayIndex = DateTime(start.year, start.month, start.day).difference(DateTime(now.year, now.month, now.day)).inDays;
    double penalty(String? sid) {
      if (sid == null) return 1.0;
      var p = 1.0;
      if (lastSubjectByDay[dayKey] == sid) p *= 0.6;
      if ((perDaySubject['$dayKey|$sid'] ?? 0) >= 2) p *= 0.5;
      return p;
    }

    double? bestScore;
    StudyTask? bestTask;
    Subject? bestSubject;
    String reason = '';

    for (final t in tasks) {
      if ((remaining[t.id] ?? 0) <= 0) continue;
      final due = t.dueAt;
      if (due != null && !start.isBefore(due)) continue;
      final daysLeft = due != null ? due.difference(start).inSeconds / 86400 : 30.0;
      var score = (_priorityWeight[t.priority] ?? 2.0) * (1 + 3 / (math.max(daysLeft, 0) + 1));
      if (t.type == TaskType.exam) score *= 1.2;
      score += 0.5 * (need[t.subjectId] ?? 0.5);
      score *= penalty(t.subjectId);
      if (bestScore == null || score > bestScore) {
        bestScore = score;
        bestTask = t;
        bestSubject = null;
        reason = _taskReason(t, daysLeft);
      }
    }

    if ((dayMinutes[dayKey] ?? 0) < goal) {
      for (final subject in data.subjects) {
        final weekly = subject.targetMinutesPerWeek > 0 ? subject.targetMinutesPerWeek : defaultWeeklyTarget;
        // Pro-rate over the horizon so revision is spread across the days.
        final target = weekly * horizonWeeks * (0.75 + 0.5 * need[subject.id]!) * (dayIndex + 1) / math.max(days, 1);
        final deficit = target > 0 ? 1 - (allocated[subject.id] ?? 0) / target : 0.0;
        if (deficit <= 0) continue;
        final score = (1.0 + 2 * need[subject.id]!) * deficit * penalty(subject.id);
        if (bestScore == null || score > bestScore) {
          bestScore = score;
          bestTask = null;
          bestSubject = subject;
          reason = _revisionReason(stats[subject.id]!, subject, now);
        }
      }
    }

    if (bestScore == null) continue;
    late final int minutes;
    late final String? sid;
    late final String title;
    if (bestTask != null) {
      minutes = math.min(length, math.max(remaining[bestTask.id]!, minSessionMinutes));
      remaining[bestTask.id] = remaining[bestTask.id]! - minutes;
      sid = bestTask.subjectId;
      title = bestTask.title;
    } else {
      minutes = length;
      sid = bestSubject!.id;
      title = '${bestSubject.name} – ${stats[sid]!.level == SubjectLevel.weak ? 'focused practice' : 'revision'}';
    }
    dayMinutes.update(dayKey, (m) => m + minutes, ifAbsent: () => minutes);
    if (sid != null) {
      allocated.update(sid, (m) => m + minutes, ifAbsent: () => minutes);
      lastSubjectByDay[dayKey] = sid;
      perDaySubject.update('$dayKey|$sid', (c) => c + 1, ifAbsent: () => 1);
    }
    newSessions.add(StudySession(
      subjectId: sid,
      taskId: bestTask?.id,
      title: title,
      start: isoLocal(start),
      durationMinutes: minutes,
      source: SessionSource.auto,
      notes: reason,
    ));
  }

  final horizonEnd = now.add(Duration(days: days));
  final atRisk = [
    for (final t in tasks)
      if ((remaining[t.id] ?? 0) > 0 && t.dueAt != null && !t.dueAt!.isAfter(horizonEnd))
        AtRiskTask(t, remaining[t.id]!),
  ];
  return PlanResult(newSessions, kept, atRisk);
}

/// Generate a plan and write it into [data]. Returns the plan.
PlanResult applyPlan(PlannerData data, DateTime now, {int days = 7}) {
  final plan = generatePlan(data, now, days: days);
  data.sessions = [...plan.kept, ...plan.sessions];
  return plan;
}

String _taskReason(StudyTask t, double daysLeft) {
  const prio = {1: 'low', 2: 'medium', 3: 'high'};
  final String when;
  if (t.due == null) {
    when = 'no deadline';
  } else if (daysLeft < 1) {
    when = 'due today';
  } else if (daysLeft < 2) {
    when = 'due tomorrow';
  } else {
    when = 'due in ${daysLeft.floor()} days';
  }
  final type = t.type.name[0].toUpperCase() + t.type.name.substring(1);
  return '$type $when · ${prio[t.priority] ?? 'medium'} priority';
}

String _revisionReason(SubjectStats stat, Subject subject, DateTime now) {
  final exam = parseDue(subject.examDate);
  if (exam != null && !exam.isBefore(now) && exam.difference(now).inDays <= 14) {
    return 'Exam in ${exam.difference(now).inDays} days – revision';
  }
  if (stat.level == SubjectLevel.weak) return 'Weak area – extra practice';
  return 'Keeping up with weekly target';
}
