"""Deterministic automatic study planner (works without any AI).

Mirrored by ``app/lib/services/planner.dart`` – keep both in sync.

Algorithm
---------
1. Drop future sessions previously generated by the planner (``source ==
   "auto"`` and still ``planned``); everything else the student scheduled or
   logged is kept and treated as busy time.
2. Cut each day's availability windows into ``session_minutes`` slots with
   ``break_minutes`` in between, skip past/busy slots and keep at most
   ``max_sessions_per_day`` per day, preferring the student's preferred time
   of day.
3. Fill slots chronologically. Each slot goes to the best candidate:

   * open tasks (by priority and closeness of the deadline, plus how weak the
     subject is), or
   * a revision session for a subject that is behind its weekly target,
     weighted towards weak/difficult subjects and upcoming exams.

   Repeating the subject of the previous slot is penalised (interleaving).
4. Tasks that cannot be fully scheduled before their deadline are reported as
   at risk.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timedelta
from typing import Any

from .analytics import subject_stats, time_period
from .model import PRIORITY_WEIGHT, iso, new_id, parse_dt, parse_due, session_end

MIN_SESSION_MINUTES = 15
DEFAULT_WEEKLY_TARGET = 120


def subject_need(subject: dict[str, Any], strength: float, now: datetime) -> float:
    """How much extra attention a subject deserves (roughly 0..2)."""
    need = (1 - strength) + 0.3 * (float(subject.get("difficulty") or 3) - 1) / 4
    exam = parse_due(subject.get("exam_date"))
    if exam and exam >= now:
        days = (exam - now).total_seconds() / 86400
        need += max(0.0, (14 - days) / 14)
    # Emphasis suggested by the AI coach (1.0 = neutral).
    return need * max(0.5, min(2.0, float(subject.get("ai_weight") or 1.0)))


def _hm(day: datetime, value: str) -> datetime:
    h, m = (int(x) for x in value.split(":")[:2])
    if h >= 24:
        return day + timedelta(days=1)
    return day.replace(hour=h, minute=m, second=0, microsecond=0)


def build_slots(doc: dict[str, Any], now: datetime, days: int, busy: list[tuple[datetime, datetime]]) -> list[tuple[datetime, datetime]]:
    profile = doc["profile"]
    length = int(profile.get("session_minutes") or 45)
    gap = int(profile.get("break_minutes") or 0)
    per_day = int(profile.get("max_sessions_per_day") or 4)
    preferred = profile.get("preferred_time")
    availability = profile.get("availability") or {}
    earliest = now + timedelta(minutes=5)

    slots: list[tuple[datetime, datetime]] = []
    for offset in range(days):
        day = (now + timedelta(days=offset)).replace(hour=0, minute=0, second=0, microsecond=0)
        day_slots = []
        for window in availability.get(str(day.isoweekday()), []):
            t, end = _hm(day, window["start"]), _hm(day, window["end"])
            while t + timedelta(minutes=length) <= end:
                slot = (t, t + timedelta(minutes=length))
                if t >= earliest and not any(slot[0] < b_end and b_start < slot[1] for b_start, b_end in busy):
                    day_slots.append(slot)
                t += timedelta(minutes=length + gap)
        # Busy sessions already planned that day count towards the daily cap.
        taken = sum(1 for b_start, _ in busy if b_start.date() == day.date())
        day_slots.sort(key=lambda s: (time_period(s[0].hour) != preferred, s[0]))
        slots.extend(sorted(day_slots[: max(0, per_day - taken)]))
    return slots


def generate_plan(doc: dict[str, Any], now: datetime, days: int = 7) -> dict[str, Any]:
    """Return ``{"sessions": [...new auto sessions], "kept": [...], "at_risk": [...]}``."""
    kept = [
        s
        for s in doc["sessions"]
        if not (s.get("source") == "auto" and s.get("status") == "planned" and (parse_dt(s.get("start")) or now) >= now)
    ]
    busy = [
        (start, end)
        for s in kept
        if s.get("status") in ("planned", "completed")
        and (start := parse_dt(s.get("start")))
        and (end := session_end(s))
        and end > now
    ]
    slots = build_slots(doc, now, days, busy)

    stats = {s["subject_id"]: s for s in subject_stats(doc, now)}
    subjects = {s["id"]: s for s in doc["subjects"]}
    need = {sid: subject_need(s, stats[sid]["strength"], now) for sid, s in subjects.items()}

    # Minutes already planned in the horizon per subject (manual sessions).
    allocated: dict[str, int] = defaultdict(int)
    for s in kept:
        start = parse_dt(s.get("start"))
        if start and start >= now and s.get("status") == "planned" and s.get("subject_id"):
            allocated[s["subject_id"]] += int(s.get("duration_minutes") or 0)

    remaining: dict[str, int] = {}
    tasks = []
    for t in doc["tasks"]:
        if t.get("status") == "done":
            continue
        left = int(t.get("estimated_minutes") or 60) - int(t.get("completed_minutes") or 0)
        # Manually planned future sessions for the task already cover part of it.
        left -= sum(
            int(s.get("duration_minutes") or 0)
            for s in kept
            if s.get("task_id") == t["id"] and s.get("status") == "planned" and (parse_dt(s.get("start")) or now) >= now
        )
        if left > 0:
            remaining[t["id"]] = left
            tasks.append(t)

    horizon_weeks = max(days, 1) / 7
    length = int(doc["profile"].get("session_minutes") or 45)
    new_sessions: list[dict[str, Any]] = []
    last_subject_by_day: dict[str, str] = {}
    per_day_subject: dict[tuple[str, str], int] = defaultdict(int)
    goal = int(doc["profile"].get("daily_goal_minutes") or 120)
    day_minutes: dict[str, int] = defaultdict(int)
    for s in kept:
        start = parse_dt(s.get("start"))
        if start and s.get("status") in ("planned", "completed"):
            day_minutes[start.date().isoformat()] += int(s.get("duration_minutes") or 0)

    for start, end in slots:
        day_key = start.date().isoformat()
        day_index = (start.date() - now.date()).days

        def penalty(sid: str | None) -> float:
            if sid is None:
                return 1.0
            p = 1.0
            if last_subject_by_day.get(day_key) == sid:
                p *= 0.6
            if per_day_subject[(day_key, sid)] >= 2:
                p *= 0.5
            return p

        best: tuple[float, dict[str, Any]] | None = None
        for t in tasks:
            if remaining.get(t["id"], 0) <= 0:
                continue
            due = parse_due(t.get("due"))
            if due is not None and start >= due:
                continue
            days_left = (due - start).total_seconds() / 86400 if due else 30
            score = PRIORITY_WEIGHT.get(int(t.get("priority") or 2), 2.0) * (1 + 3 / (max(days_left, 0) + 1))
            if t.get("type") == "exam":
                score *= 1.2
            score += 0.5 * need.get(t.get("subject_id"), 0.5)
            score *= penalty(t.get("subject_id"))
            if best is None or score > best[0]:
                reason = _task_reason(t, days_left)
                best = (score, {"kind": "task", "task": t, "reason": reason})

        # Revision only fills the day up to the daily goal; tasks may exceed it.
        revision_ok = day_minutes[day_key] < goal
        for sid, subject in subjects.items() if revision_ok else ():
            # Weak/difficult subjects get a proportionally larger share.
            weekly = int(subject.get("target_minutes_per_week") or DEFAULT_WEEKLY_TARGET)
            target = weekly * horizon_weeks * (0.75 + 0.5 * need[sid])
            # Pro-rate over the horizon so revision is spread across the days.
            target *= (day_index + 1) / max(days, 1)
            deficit = 1 - allocated[sid] / target if target else 0
            if deficit <= 0:
                continue
            score = (1.0 + 2 * need[sid]) * deficit * penalty(sid)
            if best is None or score > best[0]:
                best = (score, {"kind": "revision", "subject": subject, "reason": _revision_reason(stats[sid], subject, now)})

        if best is None:
            continue
        choice = best[1]
        if choice["kind"] == "task":
            t = choice["task"]
            minutes = min(length, max(remaining[t["id"]], MIN_SESSION_MINUTES))
            remaining[t["id"]] -= minutes
            sid = t.get("subject_id")
            title = t["title"]
            task_id = t["id"]
        else:
            subject = choice["subject"]
            minutes = length
            sid = subject["id"]
            title = f"{subject['name']} – " + ("focused practice" if stats[sid]["level"] == "weak" else "revision")
            task_id = None
        day_minutes[day_key] += minutes
        if sid:
            allocated[sid] += minutes
            last_subject_by_day[day_key] = sid
            per_day_subject[(day_key, sid)] += 1
        new_sessions.append(
            {
                "id": new_id(),
                "subject_id": sid,
                "task_id": task_id,
                "title": title,
                "start": iso(start),
                "duration_minutes": minutes,
                "status": "planned",
                "source": "auto",
                "focus_rating": None,
                "notes": choice["reason"],
            }
        )

    at_risk = [
        {"task_id": t["id"], "title": t["title"], "unscheduled_minutes": remaining[t["id"]], "due": t.get("due")}
        for t in tasks
        if remaining.get(t["id"], 0) > 0 and parse_due(t.get("due")) and parse_due(t.get("due")) <= now + timedelta(days=days)
    ]
    return {"sessions": new_sessions, "kept": kept, "at_risk": at_risk}


def apply_plan(doc: dict[str, Any], now: datetime, days: int = 7) -> dict[str, Any]:
    """Generate a plan and write it into ``doc`` in place. Returns the plan."""
    plan = generate_plan(doc, now, days)
    doc["sessions"] = plan["kept"] + plan["sessions"]
    return plan


def _task_reason(task: dict[str, Any], days_left: float) -> str:
    prio = {1: "low", 2: "medium", 3: "high"}.get(int(task.get("priority") or 2), "medium")
    if days_left < 1:
        when = "due today"
    elif days_left < 2:
        when = "due tomorrow"
    elif days_left >= 30 and not task.get("due"):
        when = "no deadline"
    else:
        when = f"due in {int(days_left)} days"
    return f"{task.get('type', 'task').capitalize()} {when} · {prio} priority"


def _revision_reason(stat: dict[str, Any], subject: dict[str, Any], now: datetime) -> str:
    exam = parse_due(subject.get("exam_date"))
    if exam and exam >= now and (exam - now).days <= 14:
        return f"Exam in {(exam - now).days} days – revision"
    if stat["level"] == "weak":
        return "Weak area – extra practice"
    return "Keeping up with weekly target"
