// The offline Dart planner/analytics must produce exactly what the Python MCP
// server produces. Fixture generated by server/tests/make_parity_fixture.py.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:study_planner/models/planner_data.dart';
import 'package:study_planner/services/analytics.dart';
import 'package:study_planner/services/planner.dart';

void main() {
  final fixture = jsonDecode(File('test/fixtures/parity.json').readAsStringSync()) as Map<String, dynamic>;
  final now = DateTime.parse(fixture['now'] as String);
  PlannerData doc() => PlannerData.fromJson(fixture['document'] as Map<String, dynamic>);

  test('plan matches the Python planner', () {
    final plan = generatePlan(doc(), now, days: 7);
    final actual = [
      for (final s in plan.sessions)
        {
          'start': s.start,
          'duration_minutes': s.durationMinutes,
          'subject_id': s.subjectId,
          'task_id': s.taskId,
          'title': s.title,
          'notes': s.notes,
        }
    ];
    expect(actual, fixture['expected_sessions']);
    expect(plan.kept.map((s) => s.id).toList()..sort(), fixture['expected_kept_ids']);
    expect(plan.atRisk.map((r) => r.task.id).toList(), fixture['expected_at_risk']);
  });

  test('analytics match the Python analytics', () {
    final s = summarize(doc(), now);
    final expected = fixture['expected_strength'] as Map<String, dynamic>;
    for (final st in s.subjects) {
      expect(st.strength, closeTo((expected[st.subject.id] as num).toDouble(), 0.001), reason: st.subject.name);
    }
    final e = fixture['expected_summary'] as Map<String, dynamic>;
    expect(s.totalMinutes, e['total_minutes']);
    expect(s.streakDays, e['streak_days']);
    expect(s.weekMinutes, e['week_minutes']);
    expect(s.bestPeriod, e['best_period']);
    expect(s.weak.map((x) => x.subject.name).toList(), e['weak']);
    expect(s.strong.map((x) => x.subject.name).toList(), e['strong']);
  });
}
